# Generated by Django 3.2.11 on 2022-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcgImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='AcgImages'),
        ),
    ]
